spring:
  datasource:
    driverClassName: org.postgresql.Driver  # JDBC драйвър за PostgreSQL
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/docks?ssl=true&sslmode=require
    username: ${DB_USER}  # Потребителско име за базата данни
    password: ${DB_PASSWORD}  # Парола за базата данни

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update  # Автоматично актуализиране на схемата
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Hibernate диалект за PostgreSQL
        format_sql: true  # Четлив формат за SQL заявките
    defer-datasource-initialization: true  # Изчакване за инициализация на източника на данни

  sql:
    init:
      mode: never  # Не изпълнява автоматично SQL скриптове (може да го промениш на `always`, ако има нужда)

logging:
  level:
    org.hibernate.SQL: DEBUG  # Логване на изпълняваните SQL заявки
    org.hibernate.orm.jdbc.bind: TRACE  # Логване на параметрите за SQL заявки
#    com.vaadin: DEBUG  # Логване на всички съобщения от Vaadin



